### ISSUE TITLE
Failed to activate the no-caffeine-syntax theme

### ISSUE THREAD

**Issue by christopher-b** [thomaslindstrom/no-caffeine-syntax#21] opened 2017-05-16 18:56 UTC
[Enter steps to reproduce:]

1. Launch Atom

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [no-caffeine-syntax](https://github.com/thomaslindstrom/no-caffeine-syntax) package 0.18.0

### Stack Trace

Failed to activate the no-caffeine-syntax theme

```
At .syntax--source.syntax--css is undefined in /Users/cbennell/.atom/packages/no-caffeine-syntax/styles/Languages/sass.less:21:8

LessError: .syntax--source.syntax--css is undefined
  at /packages/no-caffeine-syntax/styles/Languages/sass.less:21:8
```

### Commands

```
     -0:08.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.29.24 
atom-material-syntax 1.0.6 
atomatigit 1.5.5 
csscomb 0.3.1 
emmet 2.4.3 
file-icons 2.1.5 
file-types 0.5.5 
git-plus 7.8.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
language-diff 0.7.0 
language-nginx 0.7.3 
language-puppet 0.22.0 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-erb 1.1.0 
linter-js-yaml 1.2.7 
linter-jshint 3.1.2 
linter-php 1.3.2 
linter-puppet-lint 0.8.2 
linter-ruby 1.2.5 
linter-tidy 2.3.1 
merge-conflicts 1.4.4 
move-panes 0.2.0 
no-caffeine-syntax 0.18.0 
pane-layout-plus 0.7.3 
pane-move-plus 0.3.1 
pane-split-moves-tab 0.1.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.4 
quick-editor 0.4.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
symbols-tree-view 0.14.0 
terminal-status 1.6.8 
todo-show 1.11.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.10 
```

**Comment by pixilz** [comment] 2017-05-16 23:54
Able to reproduce with a completely clean install of Atom.

**Comment by jchook** [comment] 2017-05-17 23:46
Experiencing the exact same thing.

1. I am noticing a lot of [weirdness](http://cloud.jchook.com/3g0R1H101128) with other syntax themes as well.
2. I did not update the theme to cause this problem. Makes me wonder whether Atom or LESS is the culprit.

**Comment by pixilz** [comment] 2017-05-17 23:59
I went ahead and forked to check out the problem. index.less is used to compile everything the imports should be essentially dropping the code into the file but when it imports the sass.less language file it runs into an issue with being able to find the css styles (which are basically a mixin). 

So I put a reference import into sass to the css file. That got rid of the error but another error "Cannot read property 'rules' of undefined"

With this stack trace: 
(From what I can see it is definitely a problem with the compiler and not this package but I've no idea what changed to break this)
`TypeError: Cannot read property 'rules' of undefined
    at Node.Import.doEval (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\tree\import.js:160:46)
    at Node.Import.eval (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\tree\import.js:112:23)
    at Node.Ruleset.eval (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\tree\ruleset.js:149:50)
    at module.exports (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\transform-tree.js:67:22)
    at ParseTree.toCSS (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\parse-tree.js:14:25)
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\render.js:31:40
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\parse.js:63:17
    at Object.finish [as _finish] (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\parser\parser.js:183:28)
    at Object._onSequencerEmpty (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\visitors\import-visitor.js:35:14)
    at ImportSequencer.tryRun (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\visitors\import-sequencer.js:50:14)
    at Object.run (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\visitors\import-visitor.js:29:25)
    at Object.parse (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\parser\parser.js:189:22)
    at Object.parse (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\parse.js:61:18)
    at Object.render (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less\lib\less\render.js:25:18)
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less-cache\lib\less-cache.js:294:21
    at LessCache.module.exports.LessCache.observeImportedFilePaths (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less-cache\lib\less-cache.js:176:9)
    at LessCache.module.exports.LessCache.parseLess (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less-cache\lib\less-cache.js:293:22)
    at LessCache.module.exports.LessCache.cssForFile (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\less-cache\lib\less-cache.js:333:19)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\less-compile-cache.js:41:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\theme-manager.js:300:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\theme-manager.js:269:21)
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\package.js:543:54
    at Array.map (native)
    at ThemePackage.module.exports.Package.loadStylesheets (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\package.js:541:59)
    at ThemePackage.module.exports.Package.reloadStylesheets (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\src\package.js:856:14)
    at PackageWatcher.module.exports.PackageWatcher.loadAllStylesheets (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\dev-live-reload\lib\package-watcher.js:71:24)
    at PackageWatcher.loadAllStylesheets (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\dev-live-reload\lib\package-watcher.js:3:59)
    at PackageWatcher.module.exports.PackageWatcher.loadStylesheet (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\dev-live-reload\lib\package-watcher.js:66:19)
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\dev-live-reload\lib\watcher.js:76:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\event-kit\lib\emitter.js:141:28)
    at C:\Users\AT35\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:560:40
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by thomaslindstrom** [comment] 2017-05-18 08:04
Nice, @pixilz! I also got the same issue when updating Atom to the newest version (1.17.0).

**Comment by thomaslindstrom** [comment] 2017-05-18 09:08
Seems to be fixed now. Please try updating `no-caffeine-syntax`! ✌️

**Closed by thomaslindstrom** 2017-05-18 09:08 UTC
